#!/usr/bin/env bash

# Prepares the system for installing Vagrant and the RexBox
#~ set -e
#~ set -x

echo -e "\
             _             \n\
 _ _ _____ _| |__  _____ __ \n\
| '_/ -_) \ / '_ \/ _ \ \ / \n\
|_| \___/_\_\_.__/\___/_\_\ \n\
\n\
    Installation Script\n\
\n\
[…] Performing checks..."

if ! [ -f "./helpers.sh" ]; then
  echo "[!] Helper script missing. Aborting."
  exit 1
fi

source "./helpers.sh"

[ -d ~/rexbox ] && bye "[✓] RexBox is already installed.\n\
    Remove ~/rexbox directory from the home folder and run the \
script again."

cd installations/

bash virtualbox.sh
bash vagrant.sh
