#!/usr/bin/env bash

# Prepares the system for installing Vagrant and the RexBox
#~ set -e
#~ set -x

echo -e "\
             _             \n\
 _ _ _____ _| |__  _____ __ \n\
| '_/ -_) \ / '_ \/ _ \ \ / \n\
|_| \___/_\_\_.__/\___/_\_\ \n\
\n\
    Installation Script\n\
\n\
[…] Performing checks..."

if ! [ -d ~/rexbox ] ; then
  echo "[!] RexBox directory is missing. Clone the Git repository in your home folder:"
  echo "    $ git clone git@github.com:rexich/rexbox.git"
  echo "    and then run this script from inside the ~/rexbox directory."
  exit 0
fi

cd ~/rexbox/installations/

echo "[>] Setting up necessary programs..."
bash virtualbox.sh
bash vagrant.sh

echo -n "[>] Setting up aliases in Bash profile..."
echo 'alias rxb="cd ~/rexbox && vagrant up && vagrant ssh -c \"tmux -2\""' >> ~/.bashrc
echo 'alias rxh="cd ~/rexbox && vagrant halt"' >> ~/.bashrc
echo "done."

echo -e "[✓] RexBox installation complete.\n\
To start using RexBox, type 'rxb' to boot it up and SSH inside it.\n\
To stop the machine, type 'rxh' in your terminal.\n\
Thank you for using RexBox. I hope it will suit you well. :)"
