#!/usr/bin/env bash

echo -e "\
             _             \n\
 _ _ _____ _| |__  _____ __ \n\
| '_/ -_) \ / '_ \/ _ \ \ / \n\
|_| \___/_\_\_.__/\___/_\_\ \n\
\n\
      Provision Script\n\
 for the RexBox Vagrantfile\n\
\n\
[…] Provisioning in progress, it will take several minutes..."

bash /vagrant/provisioning/tools.sh
bash /vagrant/provisioning/ruby.sh
bash /vagrant/provisioning/erlang_elixir.sh
bash /vagrant/provisioning/docker.sh
bash /vagrant/provisioning/rabbitmq.sh
